name: release
on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - '.github/workflows/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ROOM_ID: "oc_88dfbcc32deb87cd3b664771e3aceb83"
      GPR_USR: ${{ secrets.GPR_USR }}
      GPR_KEY: ${{ secrets.GPR_KEY }}
      SEND_NOTIFICATION: 'false'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Do npm install
        run: |
          npm i -g standard-version
          npm i -g conventional-changelog-cli

      - name: Gen publish config files
        run: |
          ./gradlew genPublishConfigFiles

      - name: Publis lib
        run: |
          ./gradlew publish

      - name: Read libVersion
        id: readLibVersion
        run:
          echo ::set-output name=version::$(cat lib_version.txt)

      - name: Read changelog
        id: readChangelog
        run:
          echo ::set-output name=changelog::$(cat CHANGELOG.json)

      - name: Add git tag
        run: |
          git tag v${{ steps.readLibVersion.outputs.version }}
          git push origin v${{ steps.readLibVersion.outputs.version }}

      - name: Create Github release
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -i -u ${{secrets.GPR_USR}}:${{secrets.GPR_KEY}} https://api.github.com/repos/${{ github.repository }}/releases \
          -d '${{ steps.readChangelog.outputs.changelog }}'

      - name: Send notification
        run: |
          curl -XPOST \
          -H "Content-Type:application/json" \
          -H "X-SPACESHIP-TOKEN:${{ secrets.SPACESHIP_TOKEN }}" \
          https://spaceship.etm.tech/hubot/notify \
          -d '{"roomId":"${{ env.ROOM_ID }}","action":"${{ env.GITHUB_REPOSITORY }}","msg":"${{ github.repository }}发布了新版本，[点击查看](https://github.com/${{ github.repository }}/releases)"}'
        if: ${{ env.SEND_NOTIFICATION == 'true' }}